name: Summary Engine synchronized to Hugging Face hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HUGGINGFACE: ${{ secrets.HUGGINGFACE }}
        run: git remote add space https://hnbui:$HUGGINGFACE@huggingface.co/spaces/hnbui/summary-engine
      - name: Push to hub
        env:
          HUGGINGFACE: ${{ secrets.HUGGINGFACE }}
        run: git push --force https://hnbui:$HUGGINGFACE@huggingface.co/spaces/hnbui/summary-engine main
